logging:
  level:
    org:
      springframework:
        security: TRACE
        oauth: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000